// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package peerhealth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PeerHealthClient is the client API for PeerHealth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeerHealthClient interface {
	IsHealthy(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type peerHealthClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerHealthClient(cc grpc.ClientConnInterface) PeerHealthClient {
	return &peerHealthClient{cc}
}

func (c *peerHealthClient) IsHealthy(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/selfnoderemediation.health.PeerHealth/IsHealthy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerHealthServer is the server API for PeerHealth service.
// All implementations must embed UnimplementedPeerHealthServer
// for forward compatibility
type PeerHealthServer interface {
	IsHealthy(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedPeerHealthServer()
}

// UnimplementedPeerHealthServer must be embedded to have forward compatible implementations.
type UnimplementedPeerHealthServer struct {
}

func (UnimplementedPeerHealthServer) IsHealthy(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsHealthy not implemented")
}
func (UnimplementedPeerHealthServer) mustEmbedUnimplementedPeerHealthServer() {}

// UnsafePeerHealthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerHealthServer will
// result in compilation errors.
type UnsafePeerHealthServer interface {
	mustEmbedUnimplementedPeerHealthServer()
}

func RegisterPeerHealthServer(s grpc.ServiceRegistrar, srv PeerHealthServer) {
	s.RegisterService(&PeerHealth_ServiceDesc, srv)
}

func _PeerHealth_IsHealthy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerHealthServer).IsHealthy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfnoderemediation.health.PeerHealth/IsHealthy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerHealthServer).IsHealthy(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerHealth_ServiceDesc is the grpc.ServiceDesc for PeerHealth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerHealth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "selfnoderemediation.health.PeerHealth",
	HandlerType: (*PeerHealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsHealthy",
			Handler:    _PeerHealth_IsHealthy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/peerhealth/peerhealth.proto",
}
