// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoisonPillConfig) DeepCopyInto(out *PoisonPillConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoisonPillConfig.
func (in *PoisonPillConfig) DeepCopy() *PoisonPillConfig {
	if in == nil {
		return nil
	}
	out := new(PoisonPillConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoisonPillConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoisonPillConfigList) DeepCopyInto(out *PoisonPillConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PoisonPillConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoisonPillConfigList.
func (in *PoisonPillConfigList) DeepCopy() *PoisonPillConfigList {
	if in == nil {
		return nil
	}
	out := new(PoisonPillConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoisonPillConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoisonPillConfigSpec) DeepCopyInto(out *PoisonPillConfigSpec) {
	*out = *in
	if in.PeerApiServerTimeout != nil {
		in, out := &in.PeerApiServerTimeout, &out.PeerApiServerTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ApiCheckInterval != nil {
		in, out := &in.ApiCheckInterval, &out.ApiCheckInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PeerUpdateInterval != nil {
		in, out := &in.PeerUpdateInterval, &out.PeerUpdateInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ApiServerTimeout != nil {
		in, out := &in.ApiServerTimeout, &out.ApiServerTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PeerDialTimeout != nil {
		in, out := &in.PeerDialTimeout, &out.PeerDialTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PeerRequestTimeout != nil {
		in, out := &in.PeerRequestTimeout, &out.PeerRequestTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoisonPillConfigSpec.
func (in *PoisonPillConfigSpec) DeepCopy() *PoisonPillConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PoisonPillConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoisonPillConfigStatus) DeepCopyInto(out *PoisonPillConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoisonPillConfigStatus.
func (in *PoisonPillConfigStatus) DeepCopy() *PoisonPillConfigStatus {
	if in == nil {
		return nil
	}
	out := new(PoisonPillConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoisonPillRemediation) DeepCopyInto(out *PoisonPillRemediation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoisonPillRemediation.
func (in *PoisonPillRemediation) DeepCopy() *PoisonPillRemediation {
	if in == nil {
		return nil
	}
	out := new(PoisonPillRemediation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoisonPillRemediation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoisonPillRemediationList) DeepCopyInto(out *PoisonPillRemediationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PoisonPillRemediation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoisonPillRemediationList.
func (in *PoisonPillRemediationList) DeepCopy() *PoisonPillRemediationList {
	if in == nil {
		return nil
	}
	out := new(PoisonPillRemediationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoisonPillRemediationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoisonPillRemediationSpec) DeepCopyInto(out *PoisonPillRemediationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoisonPillRemediationSpec.
func (in *PoisonPillRemediationSpec) DeepCopy() *PoisonPillRemediationSpec {
	if in == nil {
		return nil
	}
	out := new(PoisonPillRemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoisonPillRemediationStatus) DeepCopyInto(out *PoisonPillRemediationStatus) {
	*out = *in
	if in.NodeBackup != nil {
		in, out := &in.NodeBackup, &out.NodeBackup
		*out = new(corev1.Node)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeAssumedRebooted != nil {
		in, out := &in.TimeAssumedRebooted, &out.TimeAssumedRebooted
		*out = (*in).DeepCopy()
	}
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoisonPillRemediationStatus.
func (in *PoisonPillRemediationStatus) DeepCopy() *PoisonPillRemediationStatus {
	if in == nil {
		return nil
	}
	out := new(PoisonPillRemediationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoisonPillRemediationTemplate) DeepCopyInto(out *PoisonPillRemediationTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoisonPillRemediationTemplate.
func (in *PoisonPillRemediationTemplate) DeepCopy() *PoisonPillRemediationTemplate {
	if in == nil {
		return nil
	}
	out := new(PoisonPillRemediationTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoisonPillRemediationTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoisonPillRemediationTemplateList) DeepCopyInto(out *PoisonPillRemediationTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PoisonPillRemediationTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoisonPillRemediationTemplateList.
func (in *PoisonPillRemediationTemplateList) DeepCopy() *PoisonPillRemediationTemplateList {
	if in == nil {
		return nil
	}
	out := new(PoisonPillRemediationTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoisonPillRemediationTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoisonPillRemediationTemplateResource) DeepCopyInto(out *PoisonPillRemediationTemplateResource) {
	*out = *in
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoisonPillRemediationTemplateResource.
func (in *PoisonPillRemediationTemplateResource) DeepCopy() *PoisonPillRemediationTemplateResource {
	if in == nil {
		return nil
	}
	out := new(PoisonPillRemediationTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoisonPillRemediationTemplateSpec) DeepCopyInto(out *PoisonPillRemediationTemplateSpec) {
	*out = *in
	out.Template = in.Template
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoisonPillRemediationTemplateSpec.
func (in *PoisonPillRemediationTemplateSpec) DeepCopy() *PoisonPillRemediationTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(PoisonPillRemediationTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoisonPillRemediationTemplateStatus) DeepCopyInto(out *PoisonPillRemediationTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoisonPillRemediationTemplateStatus.
func (in *PoisonPillRemediationTemplateStatus) DeepCopy() *PoisonPillRemediationTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(PoisonPillRemediationTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
