//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfNodeRemediation) DeepCopyInto(out *SelfNodeRemediation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfNodeRemediation.
func (in *SelfNodeRemediation) DeepCopy() *SelfNodeRemediation {
	if in == nil {
		return nil
	}
	out := new(SelfNodeRemediation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelfNodeRemediation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfNodeRemediationConfig) DeepCopyInto(out *SelfNodeRemediationConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfNodeRemediationConfig.
func (in *SelfNodeRemediationConfig) DeepCopy() *SelfNodeRemediationConfig {
	if in == nil {
		return nil
	}
	out := new(SelfNodeRemediationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelfNodeRemediationConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfNodeRemediationConfigList) DeepCopyInto(out *SelfNodeRemediationConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SelfNodeRemediationConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfNodeRemediationConfigList.
func (in *SelfNodeRemediationConfigList) DeepCopy() *SelfNodeRemediationConfigList {
	if in == nil {
		return nil
	}
	out := new(SelfNodeRemediationConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelfNodeRemediationConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfNodeRemediationConfigSpec) DeepCopyInto(out *SelfNodeRemediationConfigSpec) {
	*out = *in
	if in.PeerApiServerTimeout != nil {
		in, out := &in.PeerApiServerTimeout, &out.PeerApiServerTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ApiCheckInterval != nil {
		in, out := &in.ApiCheckInterval, &out.ApiCheckInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PeerUpdateInterval != nil {
		in, out := &in.PeerUpdateInterval, &out.PeerUpdateInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ApiServerTimeout != nil {
		in, out := &in.ApiServerTimeout, &out.ApiServerTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PeerDialTimeout != nil {
		in, out := &in.PeerDialTimeout, &out.PeerDialTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PeerRequestTimeout != nil {
		in, out := &in.PeerRequestTimeout, &out.PeerRequestTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.CustomDsTolerations != nil {
		in, out := &in.CustomDsTolerations, &out.CustomDsTolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfNodeRemediationConfigSpec.
func (in *SelfNodeRemediationConfigSpec) DeepCopy() *SelfNodeRemediationConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SelfNodeRemediationConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfNodeRemediationConfigStatus) DeepCopyInto(out *SelfNodeRemediationConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfNodeRemediationConfigStatus.
func (in *SelfNodeRemediationConfigStatus) DeepCopy() *SelfNodeRemediationConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SelfNodeRemediationConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfNodeRemediationList) DeepCopyInto(out *SelfNodeRemediationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SelfNodeRemediation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfNodeRemediationList.
func (in *SelfNodeRemediationList) DeepCopy() *SelfNodeRemediationList {
	if in == nil {
		return nil
	}
	out := new(SelfNodeRemediationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelfNodeRemediationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfNodeRemediationSpec) DeepCopyInto(out *SelfNodeRemediationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfNodeRemediationSpec.
func (in *SelfNodeRemediationSpec) DeepCopy() *SelfNodeRemediationSpec {
	if in == nil {
		return nil
	}
	out := new(SelfNodeRemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfNodeRemediationStatus) DeepCopyInto(out *SelfNodeRemediationStatus) {
	*out = *in
	if in.TimeAssumedRebooted != nil {
		in, out := &in.TimeAssumedRebooted, &out.TimeAssumedRebooted
		*out = (*in).DeepCopy()
	}
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfNodeRemediationStatus.
func (in *SelfNodeRemediationStatus) DeepCopy() *SelfNodeRemediationStatus {
	if in == nil {
		return nil
	}
	out := new(SelfNodeRemediationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfNodeRemediationTemplate) DeepCopyInto(out *SelfNodeRemediationTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfNodeRemediationTemplate.
func (in *SelfNodeRemediationTemplate) DeepCopy() *SelfNodeRemediationTemplate {
	if in == nil {
		return nil
	}
	out := new(SelfNodeRemediationTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelfNodeRemediationTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfNodeRemediationTemplateList) DeepCopyInto(out *SelfNodeRemediationTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SelfNodeRemediationTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfNodeRemediationTemplateList.
func (in *SelfNodeRemediationTemplateList) DeepCopy() *SelfNodeRemediationTemplateList {
	if in == nil {
		return nil
	}
	out := new(SelfNodeRemediationTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SelfNodeRemediationTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfNodeRemediationTemplateResource) DeepCopyInto(out *SelfNodeRemediationTemplateResource) {
	*out = *in
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfNodeRemediationTemplateResource.
func (in *SelfNodeRemediationTemplateResource) DeepCopy() *SelfNodeRemediationTemplateResource {
	if in == nil {
		return nil
	}
	out := new(SelfNodeRemediationTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfNodeRemediationTemplateSpec) DeepCopyInto(out *SelfNodeRemediationTemplateSpec) {
	*out = *in
	out.Template = in.Template
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfNodeRemediationTemplateSpec.
func (in *SelfNodeRemediationTemplateSpec) DeepCopy() *SelfNodeRemediationTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(SelfNodeRemediationTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfNodeRemediationTemplateStatus) DeepCopyInto(out *SelfNodeRemediationTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfNodeRemediationTemplateStatus.
func (in *SelfNodeRemediationTemplateStatus) DeepCopy() *SelfNodeRemediationTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(SelfNodeRemediationTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
